### ISSUE TITLE
Server Crash When Trying To Use Liroth Splitter

### ISSUE THREAD

**Issue by CloudTheWolf** [decodinatorX/Liroth-Revamped-Fabric#17] opened 2023-03-10 13:08 UTC
**Mod Version:**

1.1.9_1.19.2

**MC Version:**

1.19.2

**Fabric Version:**

0.14.15

**Mode:** 

 Multiplayer (Server)

**Issue:**

When trying to use the Liroth Splitter the server will crash.
This does not happen in Single Player or Single Player (Open LAN) modes.

**Error:**

Exception in server tick loop - Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:menu / liroth:liroth_splitter])

**Logs:**
https://mclo.gs/mglnHXm

**Full list of mods used**

    [FABRIC/QUILT] Disable Custom Worlds Advice (by rdvdev2)
    Ad Astra (by AlexNijjar)
    Ad Astra!: Giselle Addon (by 지젤쟝다)
    Additional Structures (Fabric) (by XxRexRaptorxX)
    Almost Unified (by TeamAlmostReliable)
    AmbientSounds 5 (by CreativeMD)
    AppleSkin (by squeek502)
    Architectury API (Fabric/Forge) (by shedaniel)
    BCLib (by Quiqueck)
    Better Animal Models (by cybercat5555)
    Better Animals Plus (by cybercat5555)
    Better Animations Collection (by Fuzs_)
    Better Beds (by Motschen)
    Better Combat [Fabric & Forge] (by daedelus_dev)
    Better Compatibility Checker (by Gaz_)
    Better Fps - Render Distance[Fabric] (by someaddon)
    Better Furnaces Reforged (by Wilyicaro)
    Better Safe Bed (by frankv_)
    Better Third Person (by Socolio)
    BetterEnd (by Quiqueck)
    BetterF3 (by cominixo)
    BetterNether (by Quiqueck)
    Blur (Fabric) (by Motschen)
    Bookshelf (by DarkhaxDev)
    Botarium (by CodexAdrian)
    Camera Utils (by henkelmax)
    Cardinal Components (by UpcraftLP)
    Carry On (by Tschipp)
    Cave Spelunking[Forge/Fabric] (by someaddon)
    Chunk Sending[Forge/Fabric] (by someaddon)
    Chunky (Fabric) (by pop4959)
    Cloth Config API (Fabric/Forge) (by shedaniel)
    Clumps (by Jaredlll08)
    Collective (by Serilum)
    Combat Roll [Fabric & Forge] (by daedelus_dev)
    Comforts (Fabric 1.16.5 - 1.19.2) (by TheIllusiveC4)
    Compressed Items! (by Nibaru)
    Compressed Mod (by Nibaru)
    Connectivity[Forge/Fabric] (by someaddon)
    Controlling (by Jaredlll08)
    Create Crafts & Additions (by MRHminer)
    Create Deco Fabric (by talrey)
    Create Fabric (by tropheusj)
    Create: Extended Flywheels Fabric (by Rabbitminers)
    CreativeCore (by CreativeMD)
    Croptopia (by thethonk)
    Default Options (Fabric Edition) (by BlayTheNinth)
    Double Doors (by Serilum)
    Dynamic Music Updated (by celestotototomm)
    Dynamic View[Fabric] (by someaddon)
    Eating Animation [Fabric] (by theone_ss)
    Ecologics (by SameDifferent)
    Enhanced Attack Indicator (by Minenash)
    Entity Culling Fabric/Forge (by tr9zw)
    Eroding Stone Entities (by Serilum)
    Exordium (by tr9zw)
    Fabric API (by modmuss50)
    Fabric Waystones (by LordDeatHunter)
    Factory API (by Wilyicaro)
    FallingTree (Forge&Fabric) (by rakambda)
    FerriteCore (Fabric) (by malte0811)
    First-person Model (Forge/Fabric) (by tr9zw)
    Forge Config API Port [Fabric] (by Fuzs_)
    Friendly Fire (by DarkhaxDev)
    Friends&Foes - Beekeeper Hut (Fabric) (by faboslav)
    Friends&Foes - Flowery Mooblooms (Fabric) (by faboslav)
    Friends&Foes (Fabric) (by faboslav)
    GeckoLib (by ThanosGecko)
    Gravestones (by geometrically_)
    Grim's Transportables (by TheGrimsey)
    Harvest with ease (by Crystal_Spider_)
    Healing Campfire (by Serilum)
    Incendium (by Starmute)
    Indium (by comp500)
    Infinite Music (by frinn38)
    Inventory Essentials (Fabric Edition) (by BlayTheNinth)
    Inventory Sorting (by Kyrptonaught)
    Inventory Tabs (updated) (by Andrew6rant)
    Iris Shaders (by coderbot)
    Iron Chests (Fabric) (by cyberanner)
    Jade Addons (Fabric) (by Snownee_)
    Jade 🔍 (by Snownee_)
    JourneyMap (by techbrew)
    Keebsz's Battle Towers (by keebsz_)
    Laser Bridges & Doors (by 1_block_microwave)
    Limited Chunkloading[Forge/Fabric] (by someaddon)
    Liroth: Revamped (Fabric) (by Decodinator_X)
    Litematica (by masady)
    Litematica Tool (Forge and Fabric) (by finndog_123)
    Lithium (Fabric) (by jellysquid3_)
    Login Protection[Forge/Fabric] (by someaddon)
    Macaw's Bridges (by sketch_macaw)
    Macaw's Doors (by sketch_macaw)
    Macaw's Fences and Walls (by sketch_macaw)
    Macaw's Lights and Lamps (by sketch_macaw)
    Macaw's Paintings (by sketch_macaw)
    Macaw's Paths and Pavings (by sketch_macaw)
    Macaw's Roofs (by sketch_macaw)
    Macaw's Trapdoors (by sketch_macaw)
    Macaw's Windows (by sketch_macaw)
    MaLiLib (by masady)
    Medieval Music[Forge/Fabric] (by someaddon)
    MidnightControls (by Motschen)
    MidnightControlsExtra (by Motschen)
    MidnightLib (by TeamMidnightDust)
    Mobvotes Sniffer (by YourDailyModderx)
    Mod Menu (by ProspectorDev)
    Monsters in the Closet (by Minenash)
    More Music Discs [Fabric/Forge] (by 1_block_microwave)
    Motschen's Puddles (by Motschen)
    Mouse Tweaks (by YaLTeR)
    MVS - Moog's Voyager Structures (by finndog_123)
    myLoot (by spoorn)
    NetherPortalFix (Fabric Edition) (by BlayTheNinth)
    Not Enough Animations (by tr9zw)
    Nullscape (by Starmute)
    Once Forgotten (by TheTaciturnOne)
    Oxidized (by safrodev)
    oωo (owo-lib) (by gliscowo)
    Patchouli (Fabric/Quilt) (by williewillus)
    PatchouliButton (by Globox_Z)
    Path under fence gates (Fabric/Quilt) (by Steveplays28)
    Philip's Ruins (by philipmoddev)
    Phosphor (Fabric) (by jellysquid3_)
    playerAnimator (by KosmX)
    Puzzles Lib [Forge & Fabric] (by Fuzs_)
    Quality of Life (QoL) Fixes (by spoorn)
    Realistic Sleep (Fabric/Quilt) (by Steveplays28)
    Regions Unexplored (forge/fabric) (by UHQ_GAMES)
    Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)
    Resourceful Config (by ThatGravyBoat)
    Resourceful Lib (by ThatGravyBoat)
    Restart Server (Fabric/Quilt) (by Steveplays28)
    Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
    Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
    Simple Copper Pipes (by AViewFromTheTop)
    Simple Voice Chat (by henkelmax)
    Sodium (by jellysquid3_)
    Sound Physics Remastered (by henkelmax)
    spark (by Iucko)
    SpoornPacks (by spoorn)
    Stack Refill (by Serilum)
    Stoneholm, Underground Villages (Fabric) (by TheGrimsey)
    Structory (by botanydev)
    Structory: Towers (by botanydev)
    Tectonic (by apollounknowndev)
    TerraBlender (Fabric) (by TheAdubbz)
    Terralith (by Starmute)
    Terrestria (by coderbot)
    The Graveyard (FABRIC) (by finallion_13)
    The Graveyard Biomes (FABRIC) (by finallion_13)
    The Missing Nugget [Fabric/Forge] (by 1_block_microwave)
    This Rocks! (by Motschen)
    Towns and Towers (by Biban_Auriu)
    Traveler's Backpack [Fabric] (by Tiviacz1337)
    Traverse (by ProspectorDev)
    Village Spawn Point (by Serilum)
    Villager Names (by Serilum)
    Villager Names (Fabric) (by YumatanGames)
    Visual Workbench (by Fuzs_)
    Wabi-Sabi Structures [FABRIC] (by WillFord27)
    Wavey Capes (by tr9zw)
    What The Bucket (by DarkhaxDev)
    William Wythers' Overhauled Overworld (by Cristelknight)
    World Name Generator (by Vulp35_)
    YDM's Glare (by YourDailyModderx)
    YDM's Red Panda (by YourDailyModderx)
    YUNG's API (Fabric) (by YUNGNICKYOUNG)
    YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)
    YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)
    YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)
    YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)

**Comment by decodinatorX** [comment] 2023-03-11 02:05
Interesting, I will get to work on what may be causing this frozen registry error ASAP, thank you for bringing this to my attention!

**Comment by decodinatorX** [comment] 2023-03-21 23:45
I am unable to recreate this bug within my build of Liroth Revamped, so I suspect that it is some compat issue as the freezing of the registries hasn't been an issue until now, so for the time being I will label this as a "Won't Fix" as I am not very enthusiastic about scrounging through an entire modlist to figure out which mod is causing this issue, I apologize for the inconvenience.

**Comment by noncom** [comment] 2023-09-17 12:12
Hey getting the same problem now.

The crash report: 
[crash-2023-09-17_04.18.10-server.txt](https://github.com/decodinatorX/Liroth-Revamped-Fabric/files/12642772/crash-2023-09-17_04.18.10-server.txt)

In general this looks a bit strange, because correct me if I'm wrong, but on Forge afaik usually the registries are locked after the init phase, and the classes that initialize the registries have an annotation that makes sure the loader takes them in at the start? If so, couldn't this class be similarly be directed to initialize during the initial initialization?
Please pardon me if I'm wrong since I am only vaguely familiar with Minecraft modding, and we're gettng this issue on Fabric now :)

And so, I've picked the mods that both the OP and me have:

```
Almost Unified (by TeamAlmostReliable)
AppleSkin (by squeek502)
BCLib (by Quiqueck)
Better Animations Collection (by Fuzs_)
Better Combat [Fabric & Forge] (by daedelus_dev)
Better Fps - Render Distance[Fabric] (by someaddon)
BetterEnd (by Quiqueck)
BetterF3 (by cominixo)
BetterNether (by Quiqueck)
Bookshelf (by DarkhaxDev)
Cardinal Components (by UpcraftLP)
Carry On (by Tschipp)
Cloth Config API (Fabric/Forge) (by shedaniel)
Collective (by Serilum)
Combat Roll [Fabric & Forge] (by daedelus_dev)
Comforts (Fabric 1.16.5 - 1.19.2) (by TheIllusiveC4)
Controlling (by Jaredlll08)
Croptopia (by thethonk)
Double Doors (by Serilum)
Eating Animation [Fabric] (by theone_ss)
Enhanced Attack Indicator (by Minenash)
Fabric API (by modmuss50)
Fabric Waystones (by LordDeatHunter)
FerriteCore (Fabric) (by malte0811)
Friends&Foes - Beekeeper Hut (Fabric) (by faboslav)
Friends&Foes (Fabric) (by faboslav)
GeckoLib (by ThanosGecko)
Grim's Transportables (by TheGrimsey)
Indium (by comp500)
Inventory Essentials (Fabric Edition) (by BlayTheNinth)
Inventory Sorting (by Kyrptonaught)
Iris Shaders (by coderbot)
Jade Addons (Fabric) (by Snownee_)
Jade 🔍 (by Snownee_)
JourneyMap (by techbrew)
Liroth: Revamped (Fabric) (by Decodinator_X)
Lithium (Fabric) (by jellysquid3_)
MidnightLib (by TeamMidnightDust)
Mod Menu (by ProspectorDev)
Mouse Tweaks (by YaLTeR)
Not Enough Animations (by tr9zw)
oωo (owo-lib) (by gliscowo)
Patchouli (Fabric/Quilt) (by williewillus)
Path under fence gates (Fabric/Quilt) (by Steveplays28)
Phosphor (Fabric) (by jellysquid3_)
playerAnimator (by KosmX)
Puzzles Lib [Forge & Fabric] (by Fuzs_)
Regions Unexplored (forge/fabric) (by UHQ_GAMES)
Resourceful Config (by ThatGravyBoat)
Resourceful Lib (by ThatGravyBoat)
Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Sodium (by jellysquid3_)
Sound Physics Remastered (by henkelmax)
TerraBlender (Fabric) (by TheAdubbz)
Traveler's Backpack [Fabric] (by Tiviacz1337)
William Wythers' Overhauled Overworld (by Cristelknight)
```

This lowers the scope significantly, especially that I think most of these mods, like the cosmetic ones, would have nothing to do with this issue.

I will test the compatibility of these mods with Liroth and post my findings soon.

**Comment by noncom** [comment] 2023-09-17 12:40
Alright, that was faster than I expected :D

The server crashed with only Liroth installed, and nothing else except its automatically installed dependencies:
[crash-2023-09-17_15.38.07-server.txt](https://github.com/decodinatorX/Liroth-Revamped-Fabric/files/12642829/crash-2023-09-17_15.38.07-server.txt)

Please note:
**This reproduces only in the server + client scenario**.
**It does not reproduce in singleplayer.**
In singleplayer I can open the Splitter GUI just fine. 

It is irrelevant, but please note: adding Liroth automatically adds the Mod Menu mod of version `modmenu-2.0.17.jar `, which is the latest version available on CurseForge, but which is not compatible with `Fabric-0.14.22`, and so I replace it with the newer version `modmenu-4.1.0.jar`, available from Modrinth. This mod, however, is purely client-side so I don't include it on the server, and it doesn't play any role in this issue. I will create a separate issue about it.

**Comment by noncom** [comment] 2023-09-18 18:02
If you don't mind, I would really appreciate some feedback on this and maybe some hint on if we can expect a fix on this anytime soon.

The thing is that if this takes long (or going to stay as "won't fix"), I would need to (temporarily?) disable/remove Liroth from my server so that the users stop crashing it. As that would require quite a number of additional moves and hassle, it would be cool to know if it's worth doing that now or maybe not.

**Comment by decodinatorX** [comment] 2023-09-25 00:38
I apologize, I will get to this some point, I wouldn't expect it too too soon, as I have been away from the mc modding community for a moment, but I do plan on a return fairly soon.

**Comment by noncom** [comment] 2023-09-25 12:18
Hey, thanks for the reply!

Yeah, sure, no problem. I totally understand :D
I'll be glad to reopen the Liroth exploration front when that becomes possible.

Or maybe I'll try to substitute the Splitter recipes with some custom ones in some other machines for the time being.
I'll see what I can do for now!

Great mod!

**Comment by decodinatorX** [comment] 2023-10-02 04:51
Fixed in dev build.

**Closed as completed by decodinatorX** 2023-10-02 04:51 UTC
Labels: bug, wontfix

**Comment by CANAPELEVRAI** [comment] 2023-10-16 04:06
> **Mod Version:**
> 
> 1.1.9_1.19.2
> 
> **MC Version:**
> 
> 1.19.2
> 
> **Fabric Version:**
> 
> 0.14.15
> 
> **Mode:**
> 
> Multiplayer (Server)
> 
> **Issue:**
> 
> When trying to use the Liroth Splitter the server will crash. This does not happen in Single Player or Single Player (Open LAN) modes.
> 
> **Error:**
> 
> Exception in server tick loop - Caused by: java.lang.IllegalStateException: Registry is already frozen (trying to add key ResourceKey[minecraft:menu / liroth:liroth_splitter])
> 
> **Logs:** https://mclo.gs/mglnHXm
> 
> **Full list of mods used**
> 
> ```
> [FABRIC/QUILT] Disable Custom Worlds Advice (by rdvdev2)
> Ad Astra (by AlexNijjar)
> Ad Astra!: Giselle Addon (by 지젤쟝다)
> Additional Structures (Fabric) (by XxRexRaptorxX)
> Almost Unified (by TeamAlmostReliable)
> AmbientSounds 5 (by CreativeMD)
> AppleSkin (by squeek502)
> Architectury API (Fabric/Forge) (by shedaniel)
> BCLib (by Quiqueck)
> Better Animal Models (by cybercat5555)
> Better Animals Plus (by cybercat5555)
> Better Animations Collection (by Fuzs_)
> Better Beds (by Motschen)
> Better Combat [Fabric & Forge] (by daedelus_dev)
> Better Compatibility Checker (by Gaz_)
> Better Fps - Render Distance[Fabric] (by someaddon)
> Better Furnaces Reforged (by Wilyicaro)
> Better Safe Bed (by frankv_)
> Better Third Person (by Socolio)
> BetterEnd (by Quiqueck)
> BetterF3 (by cominixo)
> BetterNether (by Quiqueck)
> Blur (Fabric) (by Motschen)
> Bookshelf (by DarkhaxDev)
> Botarium (by CodexAdrian)
> Camera Utils (by henkelmax)
> Cardinal Components (by UpcraftLP)
> Carry On (by Tschipp)
> Cave Spelunking[Forge/Fabric] (by someaddon)
> Chunk Sending[Forge/Fabric] (by someaddon)
> Chunky (Fabric) (by pop4959)
> Cloth Config API (Fabric/Forge) (by shedaniel)
> Clumps (by Jaredlll08)
> Collective (by Serilum)
> Combat Roll [Fabric & Forge] (by daedelus_dev)
> Comforts (Fabric 1.16.5 - 1.19.2) (by TheIllusiveC4)
> Compressed Items! (by Nibaru)
> Compressed Mod (by Nibaru)
> Connectivity[Forge/Fabric] (by someaddon)
> Controlling (by Jaredlll08)
> Create Crafts & Additions (by MRHminer)
> Create Deco Fabric (by talrey)
> Create Fabric (by tropheusj)
> Create: Extended Flywheels Fabric (by Rabbitminers)
> CreativeCore (by CreativeMD)
> Croptopia (by thethonk)
> Default Options (Fabric Edition) (by BlayTheNinth)
> Double Doors (by Serilum)
> Dynamic Music Updated (by celestotototomm)
> Dynamic View[Fabric] (by someaddon)
> Eating Animation [Fabric] (by theone_ss)
> Ecologics (by SameDifferent)
> Enhanced Attack Indicator (by Minenash)
> Entity Culling Fabric/Forge (by tr9zw)
> Eroding Stone Entities (by Serilum)
> Exordium (by tr9zw)
> Fabric API (by modmuss50)
> Fabric Waystones (by LordDeatHunter)
> Factory API (by Wilyicaro)
> FallingTree (Forge&Fabric) (by rakambda)
> FerriteCore (Fabric) (by malte0811)
> First-person Model (Forge/Fabric) (by tr9zw)
> Forge Config API Port [Fabric] (by Fuzs_)
> Friendly Fire (by DarkhaxDev)
> Friends&Foes - Beekeeper Hut (Fabric) (by faboslav)
> Friends&Foes - Flowery Mooblooms (Fabric) (by faboslav)
> Friends&Foes (Fabric) (by faboslav)
> GeckoLib (by ThanosGecko)
> Gravestones (by geometrically_)
> Grim's Transportables (by TheGrimsey)
> Harvest with ease (by Crystal_Spider_)
> Healing Campfire (by Serilum)
> Incendium (by Starmute)
> Indium (by comp500)
> Infinite Music (by frinn38)
> Inventory Essentials (Fabric Edition) (by BlayTheNinth)
> Inventory Sorting (by Kyrptonaught)
> Inventory Tabs (updated) (by Andrew6rant)
> Iris Shaders (by coderbot)
> Iron Chests (Fabric) (by cyberanner)
> Jade Addons (Fabric) (by Snownee_)
> Jade 🔍 (by Snownee_)
> JourneyMap (by techbrew)
> Keebsz's Battle Towers (by keebsz_)
> Laser Bridges & Doors (by 1_block_microwave)
> Limited Chunkloading[Forge/Fabric] (by someaddon)
> Liroth: Revamped (Fabric) (by Decodinator_X)
> Litematica (by masady)
> Litematica Tool (Forge and Fabric) (by finndog_123)
> Lithium (Fabric) (by jellysquid3_)
> Login Protection[Forge/Fabric] (by someaddon)
> Macaw's Bridges (by sketch_macaw)
> Macaw's Doors (by sketch_macaw)
> Macaw's Fences and Walls (by sketch_macaw)
> Macaw's Lights and Lamps (by sketch_macaw)
> Macaw's Paintings (by sketch_macaw)
> Macaw's Paths and Pavings (by sketch_macaw)
> Macaw's Roofs (by sketch_macaw)
> Macaw's Trapdoors (by sketch_macaw)
> Macaw's Windows (by sketch_macaw)
> MaLiLib (by masady)
> Medieval Music[Forge/Fabric] (by someaddon)
> MidnightControls (by Motschen)
> MidnightControlsExtra (by Motschen)
> MidnightLib (by TeamMidnightDust)
> Mobvotes Sniffer (by YourDailyModderx)
> Mod Menu (by ProspectorDev)
> Monsters in the Closet (by Minenash)
> More Music Discs [Fabric/Forge] (by 1_block_microwave)
> Motschen's Puddles (by Motschen)
> Mouse Tweaks (by YaLTeR)
> MVS - Moog's Voyager Structures (by finndog_123)
> myLoot (by spoorn)
> NetherPortalFix (Fabric Edition) (by BlayTheNinth)
> Not Enough Animations (by tr9zw)
> Nullscape (by Starmute)
> Once Forgotten (by TheTaciturnOne)
> Oxidized (by safrodev)
> oωo (owo-lib) (by gliscowo)
> Patchouli (Fabric/Quilt) (by williewillus)
> PatchouliButton (by Globox_Z)
> Path under fence gates (Fabric/Quilt) (by Steveplays28)
> Philip's Ruins (by philipmoddev)
> Phosphor (Fabric) (by jellysquid3_)
> playerAnimator (by KosmX)
> Puzzles Lib [Forge & Fabric] (by Fuzs_)
> Quality of Life (QoL) Fixes (by spoorn)
> Realistic Sleep (Fabric/Quilt) (by Steveplays28)
> Regions Unexplored (forge/fabric) (by UHQ_GAMES)
> Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)
> Resourceful Config (by ThatGravyBoat)
> Resourceful Lib (by ThatGravyBoat)
> Restart Server (Fabric/Quilt) (by Steveplays28)
> Roughly Enough Items Fabric/Forge (REI) (by shedaniel)
> Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
> Simple Copper Pipes (by AViewFromTheTop)
> Simple Voice Chat (by henkelmax)
> Sodium (by jellysquid3_)
> Sound Physics Remastered (by henkelmax)
> spark (by Iucko)
> SpoornPacks (by spoorn)
> Stack Refill (by Serilum)
> Stoneholm, Underground Villages (Fabric) (by TheGrimsey)
> Structory (by botanydev)
> Structory: Towers (by botanydev)
> Tectonic (by apollounknowndev)
> TerraBlender (Fabric) (by TheAdubbz)
> Terralith (by Starmute)
> Terrestria (by coderbot)
> The Graveyard (FABRIC) (by finallion_13)
> The Graveyard Biomes (FABRIC) (by finallion_13)
> The Missing Nugget [Fabric/Forge] (by 1_block_microwave)
> This Rocks! (by Motschen)
> Towns and Towers (by Biban_Auriu)
> Traveler's Backpack [Fabric] (by Tiviacz1337)
> Traverse (by ProspectorDev)
> Village Spawn Point (by Serilum)
> Villager Names (by Serilum)
> Villager Names (Fabric) (by YumatanGames)
> Visual Workbench (by Fuzs_)
> Wabi-Sabi Structures [FABRIC] (by WillFord27)
> Wavey Capes (by tr9zw)
> What The Bucket (by DarkhaxDev)
> William Wythers' Overhauled Overworld (by Cristelknight)
> World Name Generator (by Vulp35_)
> YDM's Glare (by YourDailyModderx)
> YDM's Red Panda (by YourDailyModderx)
> YUNG's API (Fabric) (by YUNGNICKYOUNG)
> YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)
> YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)
> YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)
> YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)
> ```




Hello I have the same problem what i do please ^^'
